export const ADD_CARD_CID = "ADD_CARD";
export const CHANGE_CARD_TEXT_CID = "CHANGE_CARD_TEXT_CID";
export const CHANGE_CARD_TITLE_CID = "CHANGE_CARD_TITLE_CID";
export const DELETE_CARD_CID = "DELETE_CARD_CID";
export const DELETE_LIST_CID = "DELETE_LIST_CID";
